/**
 * Export module - generates SVG and converts to PNG
 */
import sharp from 'sharp';
import { GITHUB_THEME, DIMENSIONS } from './config/theme.js';
import { generateOverviewCard } from './charts/overview.js';
import { generatePieSVG } from './charts/pie.js';
import { generateHeatmapSVG, generateBarChartSVG } from './charts/timeline.js';

/**
 * Generate full SVG visualization
 */
export function generateSVG(stats, buckets, options = {}) {
  const width = options.width || DIMENSIONS.width;
  const height = options.height || DIMENSIONS.height;

  // Generate chart components
  const overview = generateOverviewCard(stats, buckets, { width });
  const pieChart = generatePieSVG(stats, width - 48, 340);
  const heatmap = generateHeatmapSVG(stats.byDay, width, 200);

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <style>
    text { font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif; }
    rect { transition: all 0.2s ease; }
    rect:hover { opacity: 0.8; }
  </style>

  <!-- Background -->
  <rect x="0" y="0" width="${width}" height="${height}" fill="${GITHUB_THEME.background}" rx="16"/>

  <!-- Overview Card -->
  ${overview}

  <!-- Charts Section -->
  <!-- Pie Chart (Left) -->
  <g transform="translate(24, 150)">
    <rect x="0" y="0" width="${(width / 2) - 24}" height="340" fill="${GITHUB_THEME.cardBg}" rx="${DIMENSIONS.borderRadius}"/>
    ${pieChart}
  </g>

  <!-- Bar Chart (Right) -->
  <g transform="translate(${width / 2}, 150)">
    <rect x="0" y="0" width="${(width / 2) - 24}" height="340" fill="${GITHUB_THEME.cardBg}" rx="${DIMENSIONS.borderRadius}"/>
    ${generateBarChartSVG(stats.byDay, (width / 2) - 24, 340)}
  </g>

  <!-- Heatmap Section -->
  <g transform="translate(0, 520)">
    ${heatmap}
  </g>

  <!-- Footer -->
  <text x="${width / 2}" y="${height - 20}" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" font-size="11" fill="${GITHUB_THEME.textDim}" text-anchor="middle">Generated by Token Visualizer</text>
</svg>`;
}

/**
 * Export SVG to file
 */
export async function exportSVG(svg, outputPath) {
  const fs = await import('node:fs');
  await fs.promises.mkdir(new URL('.', `file://${outputPath}`), { recursive: true });
  await fs.promises.writeFile(outputPath, svg, 'utf-8');
  return outputPath;
}

/**
 * Convert SVG to PNG using sharp
 */
export async function exportPNG(svg, outputPath) {
  const svgBuffer = Buffer.from(svg);

  await sharp(svgBuffer, { density: 144 })
    .png()
    .toFile(outputPath);

  return outputPath;
}

/**
 * Export visualization (SVG or PNG)
 */
export async function exportVisualization(stats, buckets, outputPath) {
  const svg = generateSVG(stats, buckets);

  if (outputPath.endsWith('.png')) {
    await exportPNG(svg, outputPath);
  } else {
    await exportSVG(svg, outputPath);
  }

  return outputPath;
}
